### ISSUE TITLE
Script doesn't loop through all files in provided directories

### ISSUE THREAD

**Issue by eddyshim** [nickivanov/flickr-meta-export#3]
No idea on how to debug this python script. The program only processes one image and not sure why...

**Comment by eddyshim** [comment]
Was able to figure out how use the DEBUG feature and it shows that it only processed the one image, and didn't continue onto another image.

**Comment by nickivanov** [comment]
Sorry to hear that. However, we'd need to look at the details of your case in order to find the suspected problem. Please try to post an example that I could try to reproduce. As it is now, there's not enough information to do any troubleshooting.

**Comment by eddyshim** [comment]
Of course; I should have included examples before! I did nothing to the script itself, and have attached the DEBUG output. Am fairly new to GitHub and wasn't sure on how to upload some test image and json files properly.

[DEBUG.txt](https://github.com/nickivanov/flickr-meta-export/files/5246146/DEBUG.txt)

**Comment by nickivanov** [comment]
Thanks but I'm afraid that's not enough. If you are unable to provide a full reproducible example, at least post the complete listing of both image and metadata directories (with full paths) and the exact command line you use to invoke the program.

**Comment by eddyshim** [comment]
I'm sorry for getting back to you so late; turns out I didn't put apostrophes around the target json files, as you warned, and misplaced some more apostrophes with my image and json directories.
